version: '3.8'

services:

# # NGINX
#   nginx:
#     image: nginx:latest
#     container_name: gateway
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - "8080:8080"  
#     networks:
#       - app-network
#     depends_on:
#       - authentication-service
#       - user-service
#       # - delivery-service
#       # - notification-service
#       # - order-service
#       # - payment-service
#       # - restaurant-service
#       # - shopping-cart-service

# Base de Données Global
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

# # User Services:
#   user-service:
#     build: ./user
#     container_name: user-service
#     ports:
#       - "3002:3000"  
#     networks:
#       - app-network
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/mydatabase
#     depends_on:
#       - mongo
      
# # Authentication Services:
#   authentication-service:
#     build: ./authentication
#     container_name: authentication-service
#     ports:
#       - "3001:3000"  
#     networks:
#       - app-network
# # Deliery Services:
#   delivery-service:
#     build: ./delivery
#     container_name: delivery-service
#     ports:
#       - "3003:3000"  
#     networks:
#       - app-network

# # Notification Services:
#   notification-service:
#     build: ./notification
#     container_name: notification-service
#     ports:
#       - "3004:3000"  
#     networks:
#       - app-network

# # Order Services:
#   order-service:
#     build: ./order
#     container_name: order-service
#     ports:
#       - "3005:3000"  
#     networks:
#       - app-network

# Payment Services:
  payment-service:
    build: ./payment
    container_name: payment-service
    ports:
      - "3006:3000"  
    networks:
      - app-network

# # Restaurant Services:
#   restaurant-service:
#     build: ./restaurant
#     container_name: restaurant-service
#     ports:
#       - "3007:3000"  
#     networks:
#       - app-network

# # Shopping Cart Services:
#   shopping-cart-service:
#     build: ./shopping cart
#     container_name: shopping-cart-service
#     ports:
#       - "3008:3000"  
#     networks:
#       - app-network

networks:
  app-network:
    driver: bridge
