version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"  
    networks:
      - app-network
    depends_on:
      - authentication-service
      - user-service
      - delivery-service
      - notification-service
      - order-service
      - payment-service
      - restaurant-service
      - shopping-cart-service

  authentication-service:
    build: ./authentication
    container_name: authentication-service
    ports:
      - "3001:3000"  
    networks:
      - app-network

  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "3002:3000"  
    networks:
      - app-network

  delivery-service:
    build: ./delivery
    container_name: delivery-service
    ports:
      - "3003:3000"  
    networks:
      - app-network

  notification-service:
    build: ./notification
    container_name: notification-service
    ports:
      - "3004:3000"  
    networks:
      - app-network

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "3005:3000"  
    networks:
      - app-network

  payment-service:
    build: ./payment
    container_name: payment-service
    ports:
      - "3006:3000"  
    networks:
      - app-network

  restaurant-service:
    build: ./restaurant
    container_name: restaurant-service
    ports:
      - "3007:3000"  
    networks:
      - app-network

  shopping-cart-service:
    build: ./shopping cart
    container_name: shopping-cart-service
    ports:
      - "3008:3000"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
