apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart-service
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
      - name: shopping-cart-service
        image: mamadou7120/shopping-cart-service:latest 
        ports:
        - containerPort: 3008
